# Generated by Django 5.1.2 on 2024-10-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesproduct",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
