# Generated by Django 5.1.2 on 2024-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_stripe_price_id_product_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="handle",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
